# keymaps
unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind-key x kill-pane

#unbind C-b
#set -g prefix C-Space

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

set -g default-terminal "tmux-256color"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g mode-keys vi
set -sg escape-time 10 # make delay shorter

### Copy Mode
bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"


### Plugins 
set -g @plugin 'tmux-plugins/tpm'

# catppuccin theme
#set -g @plugin "catppuccin/tmux#latest"
#set -g @catppuccin_flavour 'mocha' # latte,frappe, macchiato or mocha

set -g @plugin 'tmux-plugins/tmux-yank' # 可以将vi复制的内容存到系统剪切板中
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.config/tmux/.tmux/plugins/tpm/tpm' # Initialize TPM
